name: Code Coverage
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
